# Generated by Django 5.1.2 on 2024-11-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quest2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("altura", models.FloatField()),
                ("cintura", models.FloatField()),
                ("peso", models.FloatField()),
                ("imc", models.FloatField()),
                ("pressao", models.FloatField()),
                ("oximetria", models.FloatField()),
                ("frequencia_card", models.FloatField()),
            ],
        ),
    ]
