# Generated by Django 5.1.2 on 2024-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="quest2",
            new_name="banco_quest2",
        ),
    ]
