# Generated by Django 5.1.2 on 2024-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quest3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nausea", models.FloatField()),
                ("vomito", models.FloatField()),
                ("tontura", models.FloatField()),
                ("suor", models.FloatField()),
                ("plaidez", models.FloatField()),
                ("dorcab", models.FloatField()),
                ("cansaco", models.FloatField()),
                ("bocejo", models.FloatField()),
                ("hiperv", models.FloatField()),
                ("outros", models.CharField(max_length=500)),
            ],
        ),
    ]
