# Generated by Django 5.1.2 on 2024-11-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest3", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest3",
            old_name="plaidez",
            new_name="palidez",
        ),
    ]
