# Generated by Django 5.1.2 on 2024-11-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest3", "0002_rename_plaidez_quest3_palidez"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest3",
            name="bocejo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="cansaco",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="dorcab",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="hiperv",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="nausea",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="outros",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="palidez",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="suor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="tontura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quest3",
            name="vomito",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
