# Generated by Django 5.1.2 on 2024-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest3", "0003_alter_quest3_bocejo_alter_quest3_cansaco_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="quest3",
            new_name="banco_quest3",
        ),
    ]
