# Generated by Django 5.1.2 on 2024-11-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest1", "0002_remove_quest1_algumas_vezes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="quest1",
            new_name="banco_quest1",
        ),
    ]
