# Generated by Django 5.1.2 on 2024-11-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest1", "0003_rename_quest1_banco_quest1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="autocarros10",
            new_name="autocarros2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="aviões",
            new_name="avioes",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="aviões10",
            new_name="avioes2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="baloiços",
            new_name="baloicos",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="baloiços10",
            new_name="baloicos2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="carros10",
            new_name="carros2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="carroseis10",
            new_name="carroseis2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="comboios10",
            new_name="comboios2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="embarcacao_pequena10",
            new_name="embarcacao_pequena2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="montanha_russa10",
            new_name="montanha_russa2",
        ),
        migrations.RenameField(
            model_name="banco_quest1",
            old_name="navios10",
            new_name="navios2",
        ),
    ]
